os: linux
dist: xenial
language: python
python: "3.7"

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
    only: develop

env:
  - TASK=lint
  - TASK=fmt-travis
  - TASK=test-travis

script: make -f Makefile $TASK
